#include "havok/packfile/hkx_packfile_reader.h"
#include "common/binary_reader/binary_reader.h"

#include <cstring>
#include <string>

namespace lu::assets {

namespace {

// Sanity-check a count/length field read from the file before resize()-ing a vector to
// it. Mirrors nif_reader.cpp's bounded_count(): a malformed file can put a huge garbage
// value in an offset/length field, and without this guard resize() attempts a
// multi-gigabyte allocation that stalls rather than fails fast. Every byte of a section
// or sub-region needs at least 1 byte on disk, so a legitimate value can never exceed
// the file's remaining bytes.
size_t bounded_size(size_t value, size_t remaining_in_file, const char* what) {
    if (value > remaining_in_file) {
        throw HkxPackfileError(std::string("HKX packfile: ") + what + " size " +
                                std::to_string(value) + " exceeds remaining file data");
    }
    return value;
}

// Reads a fixed-size field and trims it at the first NUL byte (matching how
// PackfileHeader::contentsVersion and SectionHeader::sectionTag are stored: a
// fixed-size buffer that C string functions/consumers treat as NUL-terminated). The
// trailing 0xFF sentinel byte every real sample has as the field's last byte (see
// hkx_packfile_types.h) is dropped here and regenerated by the writer
// (write_fixed_str_havok_padded), rather than stored on HkxPackfile, since it's constant
// and not part of the meaningful string content.
std::string read_fixed_nul_string(BinaryReader& r, size_t field_size) {
    auto bytes = r.read_bytes(field_size);
    size_t len = 0;
    while (len < bytes.size() && bytes[len] != 0) ++len;
    return std::string(reinterpret_cast<const char*>(bytes.data()), len);
}

} // namespace

HkxPackfile hkx_packfile_parse(std::span<const uint8_t> data) {
    if (data.size() < 64) {
        throw HkxPackfileError("HKX packfile: file smaller than the 64-byte header");
    }

    BinaryReader r(data);

    uint32_t magic0 = r.read_u32();
    uint32_t magic1 = r.read_u32();
    if (magic0 != 0x57E0E057 || magic1 != 0x10C0C010) {
        throw HkxPackfileError("HKX packfile: bad magic (not a binary packfile)");
    }

    HkxPackfile file;
    HkxPackfileHeader& h = file.header;
    h.magic0 = magic0;
    h.magic1 = magic1;
    h.userTag = r.read_u32();
    h.fileVersion = r.read_u32();
    h.pointerSize = r.read_u8();
    h.littleEndian = r.read_u8();
    h.reusePaddingOptimization = r.read_u8();
    h.emptyBaseClassOptimization = r.read_u8();
    h.numSections = r.read_u32();
    h.contentsSectionIndex = r.read_u32();
    h.contentsSectionOffset = r.read_u32();
    h.contentsClassNameSectionIndex = r.read_u32();
    h.contentsClassNameSectionOffset = r.read_u32();
    h.contentsVersion = read_fixed_nul_string(r, 16);
    h.flags = r.read_u32();
    h.maxPredicate = r.read_s16();
    h.predicateArraySizePlusPadding = r.read_s16();

    // Bound numSections before resizing: the real corpus is always exactly 3, but this
    // guards against a corrupt/hostile file claiming an enormous section count (each
    // section header is 48 bytes, so a legitimate count can't exceed remaining bytes / 48).
    uint32_t num_sections = static_cast<uint32_t>(
        bounded_size(h.numSections, r.remaining() / 48, "numSections"));
    h.numSections = num_sections;

    file.sections.reserve(num_sections);
    for (uint32_t i = 0; i < num_sections; ++i) {
        HkxSectionHeader sh;
        sh.sectionTag = read_fixed_nul_string(r, 20);
        sh.absoluteDataStart = r.read_u32();
        sh.localFixupsOffset = r.read_u32();
        sh.globalFixupsOffset = r.read_u32();
        sh.virtualFixupsOffset = r.read_u32();
        sh.exportsOffset = r.read_u32();
        sh.importsOffset = r.read_u32();
        sh.endOffset = r.read_u32();
        file.sections.push_back(std::move(sh));
    }

    // Slice each section's raw bytes into sub-regions per its own offset fields. The
    // sub-region boundaries (localFixupsOffset <= globalFixupsOffset <= ... <= endOffset)
    // are section-relative; absoluteDataStart is the file-relative base. Every real
    // sampled file has these fields non-decreasing (see README.md's ordering_ok=100%
    // survey result), but a corrupt file could violate that, so each slice is bounds- and
    // order-checked before slicing rather than trusting the arithmetic blindly.
    file.section_data.reserve(num_sections);
    for (const HkxSectionHeader& sh : file.sections) {
        auto require_order = [&](uint32_t lo, uint32_t hi, const char* what) {
            if (hi < lo) {
                throw HkxPackfileError(std::string("HKX packfile: section '") + sh.sectionTag +
                                        "' has out-of-order offsets in " + what);
            }
        };
        require_order(0, sh.localFixupsOffset, "data/localFixups");
        require_order(sh.localFixupsOffset, sh.globalFixupsOffset, "localFixups/globalFixups");
        require_order(sh.globalFixupsOffset, sh.virtualFixupsOffset, "globalFixups/virtualFixups");
        require_order(sh.virtualFixupsOffset, sh.exportsOffset, "virtualFixups/exports");
        require_order(sh.exportsOffset, sh.importsOffset, "exports/imports");
        require_order(sh.importsOffset, sh.endOffset, "imports/end");

        // absoluteDataStart + endOffset must not run past the end of the file.
        if (sh.absoluteDataStart > data.size() ||
            sh.endOffset > data.size() - sh.absoluteDataStart) {
            throw HkxPackfileError(std::string("HKX packfile: section '") + sh.sectionTag +
                                    "' extends past end of file");
        }

        size_t base = sh.absoluteDataStart;
        auto slice = [&](uint32_t start, uint32_t end) {
            return std::vector<uint8_t>(data.begin() + base + start, data.begin() + base + end);
        };

        HkxSectionData sd;
        sd.data          = slice(0, sh.localFixupsOffset);
        sd.localFixups   = slice(sh.localFixupsOffset, sh.globalFixupsOffset);
        sd.globalFixups  = slice(sh.globalFixupsOffset, sh.virtualFixupsOffset);
        sd.virtualFixups = slice(sh.virtualFixupsOffset, sh.exportsOffset);
        sd.exports       = slice(sh.exportsOffset, sh.importsOffset);
        sd.imports       = slice(sh.importsOffset, sh.endOffset);
        file.section_data.push_back(std::move(sd));
    }

    return file;
}

} // namespace lu::assets
